### ISSUE TITLE
Array parameters with default values 

### ISSUE THREAD

**Issue by aalong** [mikkeloscar/gin-swagger#13]
The code produced by [this line](https://github.com/mikkeloscar/gin-swagger/blob/c7ceafbf05b9075a9b5b658e29186dddf2efe269/templates/parameter.gotmpl#L328) of the Parameter template does not correctly handle default values of type Array, writing the array directly into the template with its values as raw text. 

Example YML for a failing parameter:
```
        - name: Foo
          in: query
          description: >-
            A comma-delimited list of arbitrary values
          type: array
          items:
            type: string
          collectionFormat: csv
          default:
            - Bar
            - Bazz
            - Buzz

```

This produces the line:
`defValue := swag.SplitByFormat([Bar Bazz Buzz], "csv")`

If I understand the default templates correctly, they seem to be [using the JSON parser as a middle man](https://github.com/mikkeloscar/gin-swagger/blob/c7ceafbf05b9075a9b5b658e29186dddf2efe269/templates/parameter.gotmpl#L328) to handle these cases. Would that work for this lib as well?
