### ISSUE TITLE
Cannot define upload type in swagger file

### ISSUE THREAD

**Issue by mdonnellyli** [mikkeloscar/gin-swagger#24]
I am trying to define a file upload file

```
/upload:
     post:
       summary: Uploads a CSV file.
       consumes:
         - multipart/form-data
       parameters:
         - in: formData
           name: customers
           type: string
           format: binary
           description: The file to upload.
         - name: update
           in: query
           type: boolean
           required: false
           default: false
         - name: import_id
           in: query
           type: string
           required: false
```

But it results in broken code gen

```
restapi/operations/post_upload_parameters.go:131:14: cannot use value.(*io.ReadCloser) (type *io.ReadCloser) as type io.ReadCloser in assignment:
	*io.ReadCloser is pointer to interface, not interface
```
